apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: apps
    helm:
      parameters:
        - name: repoURL
          value: {{ .Values.repoURL }}
        - name: revision
          value: {{ .Values.revision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
